// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_CMS_URL = process.env.NEXT_PUBLIC_SUPABASE_CMS_URL;
const SUPABASE_CMS_PUBLISHABLE_KEY =
  process.env.NEXT_PUBLIC_SUPABASE_CMS_PUBLISHABLE_KEY;

if (!SUPABASE_CMS_URL || !SUPABASE_CMS_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing Supabase CMS environment variables. Please add NEXT_PUBLIC_SUPABASE_CMS_URL and NEXT_PUBLIC_SUPABASE_CMS_PUBLISHABLE_KEY to your .env file."
  );
}

// Create a custom storage implementation that safely handles localStorage
const browserStorage = {
  getItem: (key: string) => {
    if (typeof window !== 'undefined') {
      return window.localStorage.getItem(key);
    }
    return null;
  },
  setItem: (key: string, value: string) => {
    if (typeof window !== 'undefined') {
      window.localStorage.setItem(key, value);
    }
  },
  removeItem: (key: string) => {
    if (typeof window !== 'undefined') {
      window.localStorage.removeItem(key);
    }
  },
};

export const supabase = createClient<Database>(
  SUPABASE_CMS_URL,
  SUPABASE_CMS_PUBLISHABLE_KEY,
  {
    auth: {
      storage: browserStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  }
);
